# Navigation Links
#   The weight parameter defines the order links appear in the navbar.

main:
  - name: 简介
    url: /
    weight: 10

  - name: 博客
    url: blog/
    weight: 11

  - name: 默会知识
    url: blog/mohui-zhishi/
    parent: 博客
    weight: 12

  - name: 读书笔记
    url: blog/du-shu-bi-ji/
    weight: 13

  - name: 经历
    url: experience/
    weight: 14
